#!/bin/sh
./gameboy BROKER APPEARED_POKEMON Onix 2 8 1
./gameboy BROKER APPEARED_POKEMON Gengar 6 6 2 
./gameboy BROKER APPEARED_POKEMON Squirtle 5 5 3

./gameboy BROKER APPEARED_POKEMON Umbreon 10 6 4
./gameboy BROKER APPEARED_POKEMON Espeon 7 1 5
./gameboy BROKER APPEARED_POKEMON Vaporeon 4 10 6
